# Site settings
name: William Fraher's Github Blog
email: 
description: "I enjoy deep reinforcement learning, among other things."
baseurl: ""
url: "http://wfraher.github.io"
twitter_username: 
github_username:  wfraher

# Build settings
markdown: kramdown
permalink: pretty

#For disqus commenting
disqus: wfraher-github-io

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
